### ISSUE TITLE
Initial roadmap

### ISSUE THREAD

**Issue by rick** [rick/branch-deploy#4]
![image](https://github.com/rick/branch-deploy/assets/6259/74afead9-14d2-4676-858c-0543b6b7bb15)

## Goal

We (especially @jameswhite and I) have need of an efficient, (dependency-) lightweight single-purpose tool to facilitate "branch deploys", and "branch diffs" for continuing to develop "on-system" software.

This differs from the various ways and tools to deploy (micro-)services and web apps to cloud platforms, kubernetes, etc., for which there are many CI/CD tools and processes.

#### "On-system?"

By "on-system" software I mean that we are often managing the operating-system level files on a host machine. For instance, files in `/etc`, configurations of things like LDAP servers, Nagios monitoring, TFTP/PXE configurations, etc.

#### "Host?"

By "host" we mean a computer, which could be bare metal, a virtual machine (for instance in a VMWare instantiation), a container, a remote cloud-hosted instance. We expect the host to have a running OS and kernel, most often running Linux, but configuration may be minimal.

#### "branch deploys?", "branch diffs?"

[Old man voice:] Back when we worked at GitHub, we deployed software (web applications, supporting tooling, host configurations, eventually network configurations, etc.) using a specific process:

 - Develop changes via Pull Request on a new git branch
 - As changes are pushed to GitHub, CI runs to validate the changes
 - When changes need testing, "branch deploy" them (deploy that git branch of code to either a "branch lab" staging environment, or, eventually) to the production host(s) in question
 - If this deployment proves workable (via various testing and telemetry means) then the Pull Request is merged, and the deployment becomes the new production "mainline" deployment

This is often colloquially referred to as the "GitHub Flow", especially if these operations are undertaken via [ChatOps](https://speakerdeck.com/jnewland/chatops-at-github).

Over time, for changes which were less "web application software" and more likely to be systems level software (OS configurations, authorization configurations, network changes), the "branch deploy" phase was often preceded by:

 - Report on the proposed changes, on real hosts, for this branch. This would take the form of a diff, hence "branch diff".

This process, taken together with the technique of separating the deployment and setup of a systems level tool (LDAP, puppet, nagios, vault, or systems such as [Entitlements](https://github.blog/2022-06-09-introducing-entitlements-githubs-open-source-identity-and-access-management-solution/)), from the data contents of that tool -- each of which can have its own branch deployment lifecycle, is sometimes colloquially called the "KP Flow", after [Kevin Paulisse](https://github.com/kpaulisse) who refined and spread this pattern during his time at GitHub.

## Development constraints

 - The source host needs to support the language environment (ruby in this case) for the `bd` command-line tool.
 - The target host for a deployment needs a modern-ish shell (bash, dash, etc.) to run the deployment commands; `git` to clone a repository, and`rsync` to do tree diffing and deployment. It does not need to support the (ruby) language environment.
 - Testing should be full integration testing if at all possible. That is, no unit testing; definitely no mocking/stubbing tests. We should be able to use containerization to support fully sandbox real deployments during testing.

## Timeline

 - [x] get basic development tooling in place
 - [x] write a README for the CLI `bd` tool usage
 - [x] BDD test-drive the options processing for the CLI tool
 - [x] get container-sandboxed local CI working
 - [ ] get container-sandboxed GitHub Actions CI working
 - [ ] get libgit2/rugged working to generate test fixture git repositories from readable definitions
 - [ ] deploy git repo test fixtures during container testing (local and CI)
 - [ ] remote deployments (via SSH)
   - [ ] BDD develop `--diff` no-op deployments
   - [ ] BDD develop non-diff deployments
 - [ ] add support for local (as opposed to via-SSH) deployments
 - [ ] (later?) add support for running hook scripts before and after actually deploying files

**Comment by rick** [comment]
Updated roadmap pursuant to conversations with @jameswhite
